sudo: required
dist: trusty
language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
env:
  - NODE_RELEASE=6.x
before_install:
  - curl --version
  - composer self-update
  - sudo rm -rf ~/.nvm
  - curl -sL "https://deb.nodesource.com/setup_${NODE_RELEASE}" | sudo -E bash -
  - sudo apt-get install -y nodejs
  - mkdir -p build/logs
install:
  - composer install
  - npm install
script: make test
after_success:
  - travis_retry php vendor/bin/coveralls
